name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.3.5f1-webgl
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        - name: Decrypt the license file
          run: openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_SECRET_KEY }} >> .github/Unity_v2019.x.ulf
        
        # Activate unity
        - name: Activate Unity
          run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2019.x.ulf || exit 0
        
        # Build Windows and OSX
        - name: Build WebGL Player
          run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -buildTarget WebGL ./bin-win64/3DProject
        # - name: Build OSX Player
        #   run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -buildOSXUniversalPlayer ./bin-osx/3DProject.app      
        
        - name: Archive Web Build
          uses: actions/upload-artifact@v1
          with:
            name: 3DProjectWebBinary
            path: ./bin-win64

        # - name: Archive Mac Build
        #   uses: actions/upload-artifact@v1
        #   with:
        #     name: 3DProjectOSXBinary
        #     path: ./bin-osx